<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexusIntegration.Application\NexusIntegration.Application.csproj" />
    <ProjectReference Include="..\NexusIntegration.Infrastructure\NexusIntegration.Infrastructure.csproj" />
    <ProjectReference Include="..\NexusIntegration.Shared\NexusIntegration.Shared.csproj" />
  </ItemGroup>

</Project>
